name: sbt_auth_dart
description: SBTAuth flutter sdk
version: 0.2.0
repository: https://github.com/ABMatrix/sbt-auth-dart

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  eth_sig_util: ^0.0.9
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  mpc_dart: ^0.1.1
  path_provider: ^2.0.11
  web3dart: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
