name: sbt_auth_dart
description: SBTAuth flutter sdk
version: 0.4.26
repository: https://github.com/ABMatrix/sbt-auth-dart
# publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  app_links: ^3.3.0
  cryptography: ^2.0.5
  decimal: ^2.3.0
  eth_sig_util: ^0.0.9
  eventsource: ^0.4.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  mpc_dart: 0.2.6
  package_info_plus: ^2.0.0
  path_provider: ^2.0.11
  sbt_encrypt: ^0.1.3
  url_launcher: ^6.1.6
  web3dart: ^2.3.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
