name: sbt_auth_dart
description: SBTAuth flutter sdk
version: 0.2.4
repository: https://github.com/ABMatrix/sbt-auth-dart

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  app_links: ^3.3.0
  decimal: ^2.3.0
  eth_sig_util: ^0.0.9
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  mpc_dart: ^0.1.1
  package_info_plus: ^2.0.0
  path_provider: ^2.0.11
  url_launcher: ^6.1.6
  web3dart: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
